// soc_system_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 22.1 922

`timescale 1 ps / 1 ps
module soc_system_mm_interconnect_0 (
		input  wire        clk_0_clk_clk,                                             //                                           clk_0_clk.clk
		input  wire        hps_0_h2f_user2_clock_clk,                                 //                               hps_0_h2f_user2_clock.clk
		input  wire        address_span_extender_0_reset_reset_bridge_in_reset_reset, // address_span_extender_0_reset_reset_bridge_in_reset.reset
		input  wire        bridge_0_reset_reset_bridge_in_reset_reset,                //                bridge_0_reset_reset_bridge_in_reset.reset
		input  wire [27:0] bridge_0_avalon_master_address,                            //                              bridge_0_avalon_master.address
		output wire        bridge_0_avalon_master_waitrequest,                        //                                                    .waitrequest
		input  wire [7:0]  bridge_0_avalon_master_byteenable,                         //                                                    .byteenable
		input  wire        bridge_0_avalon_master_read,                               //                                                    .read
		output wire [63:0] bridge_0_avalon_master_readdata,                           //                                                    .readdata
		input  wire        bridge_0_avalon_master_write,                              //                                                    .write
		input  wire [63:0] bridge_0_avalon_master_writedata,                          //                                                    .writedata
		output wire [24:0] address_span_extender_0_windowed_slave_address,            //              address_span_extender_0_windowed_slave.address
		output wire        address_span_extender_0_windowed_slave_write,              //                                                    .write
		output wire        address_span_extender_0_windowed_slave_read,               //                                                    .read
		input  wire [63:0] address_span_extender_0_windowed_slave_readdata,           //                                                    .readdata
		output wire [63:0] address_span_extender_0_windowed_slave_writedata,          //                                                    .writedata
		output wire [0:0]  address_span_extender_0_windowed_slave_burstcount,         //                                                    .burstcount
		output wire [7:0]  address_span_extender_0_windowed_slave_byteenable,         //                                                    .byteenable
		input  wire        address_span_extender_0_windowed_slave_readdatavalid,      //                                                    .readdatavalid
		input  wire        address_span_extender_0_windowed_slave_waitrequest         //                                                    .waitrequest
	);

	wire          bridge_0_avalon_master_translator_avalon_universal_master_0_waitrequest;   // bridge_0_avalon_master_agent:av_waitrequest -> bridge_0_avalon_master_translator:uav_waitrequest
	wire   [63:0] bridge_0_avalon_master_translator_avalon_universal_master_0_readdata;      // bridge_0_avalon_master_agent:av_readdata -> bridge_0_avalon_master_translator:uav_readdata
	wire          bridge_0_avalon_master_translator_avalon_universal_master_0_debugaccess;   // bridge_0_avalon_master_translator:uav_debugaccess -> bridge_0_avalon_master_agent:av_debugaccess
	wire   [27:0] bridge_0_avalon_master_translator_avalon_universal_master_0_address;       // bridge_0_avalon_master_translator:uav_address -> bridge_0_avalon_master_agent:av_address
	wire          bridge_0_avalon_master_translator_avalon_universal_master_0_read;          // bridge_0_avalon_master_translator:uav_read -> bridge_0_avalon_master_agent:av_read
	wire    [7:0] bridge_0_avalon_master_translator_avalon_universal_master_0_byteenable;    // bridge_0_avalon_master_translator:uav_byteenable -> bridge_0_avalon_master_agent:av_byteenable
	wire          bridge_0_avalon_master_translator_avalon_universal_master_0_readdatavalid; // bridge_0_avalon_master_agent:av_readdatavalid -> bridge_0_avalon_master_translator:uav_readdatavalid
	wire          bridge_0_avalon_master_translator_avalon_universal_master_0_lock;          // bridge_0_avalon_master_translator:uav_lock -> bridge_0_avalon_master_agent:av_lock
	wire          bridge_0_avalon_master_translator_avalon_universal_master_0_write;         // bridge_0_avalon_master_translator:uav_write -> bridge_0_avalon_master_agent:av_write
	wire   [63:0] bridge_0_avalon_master_translator_avalon_universal_master_0_writedata;     // bridge_0_avalon_master_translator:uav_writedata -> bridge_0_avalon_master_agent:av_writedata
	wire    [3:0] bridge_0_avalon_master_translator_avalon_universal_master_0_burstcount;    // bridge_0_avalon_master_translator:uav_burstcount -> bridge_0_avalon_master_agent:av_burstcount
	wire          rsp_mux_src_valid;                                                         // rsp_mux:src_valid -> bridge_0_avalon_master_agent:rp_valid
	wire  [134:0] rsp_mux_src_data;                                                          // rsp_mux:src_data -> bridge_0_avalon_master_agent:rp_data
	wire          rsp_mux_src_ready;                                                         // bridge_0_avalon_master_agent:rp_ready -> rsp_mux:src_ready
	wire    [0:0] rsp_mux_src_channel;                                                       // rsp_mux:src_channel -> bridge_0_avalon_master_agent:rp_channel
	wire          rsp_mux_src_startofpacket;                                                 // rsp_mux:src_startofpacket -> bridge_0_avalon_master_agent:rp_startofpacket
	wire          rsp_mux_src_endofpacket;                                                   // rsp_mux:src_endofpacket -> bridge_0_avalon_master_agent:rp_endofpacket
	wire   [63:0] address_span_extender_0_windowed_slave_agent_m0_readdata;                  // address_span_extender_0_windowed_slave_translator:uav_readdata -> address_span_extender_0_windowed_slave_agent:m0_readdata
	wire          address_span_extender_0_windowed_slave_agent_m0_waitrequest;               // address_span_extender_0_windowed_slave_translator:uav_waitrequest -> address_span_extender_0_windowed_slave_agent:m0_waitrequest
	wire          address_span_extender_0_windowed_slave_agent_m0_debugaccess;               // address_span_extender_0_windowed_slave_agent:m0_debugaccess -> address_span_extender_0_windowed_slave_translator:uav_debugaccess
	wire   [27:0] address_span_extender_0_windowed_slave_agent_m0_address;                   // address_span_extender_0_windowed_slave_agent:m0_address -> address_span_extender_0_windowed_slave_translator:uav_address
	wire    [7:0] address_span_extender_0_windowed_slave_agent_m0_byteenable;                // address_span_extender_0_windowed_slave_agent:m0_byteenable -> address_span_extender_0_windowed_slave_translator:uav_byteenable
	wire          address_span_extender_0_windowed_slave_agent_m0_read;                      // address_span_extender_0_windowed_slave_agent:m0_read -> address_span_extender_0_windowed_slave_translator:uav_read
	wire          address_span_extender_0_windowed_slave_agent_m0_readdatavalid;             // address_span_extender_0_windowed_slave_translator:uav_readdatavalid -> address_span_extender_0_windowed_slave_agent:m0_readdatavalid
	wire          address_span_extender_0_windowed_slave_agent_m0_lock;                      // address_span_extender_0_windowed_slave_agent:m0_lock -> address_span_extender_0_windowed_slave_translator:uav_lock
	wire   [63:0] address_span_extender_0_windowed_slave_agent_m0_writedata;                 // address_span_extender_0_windowed_slave_agent:m0_writedata -> address_span_extender_0_windowed_slave_translator:uav_writedata
	wire          address_span_extender_0_windowed_slave_agent_m0_write;                     // address_span_extender_0_windowed_slave_agent:m0_write -> address_span_extender_0_windowed_slave_translator:uav_write
	wire    [3:0] address_span_extender_0_windowed_slave_agent_m0_burstcount;                // address_span_extender_0_windowed_slave_agent:m0_burstcount -> address_span_extender_0_windowed_slave_translator:uav_burstcount
	wire          address_span_extender_0_windowed_slave_agent_rf_source_valid;              // address_span_extender_0_windowed_slave_agent:rf_source_valid -> address_span_extender_0_windowed_slave_agent_rsp_fifo:in_valid
	wire  [135:0] address_span_extender_0_windowed_slave_agent_rf_source_data;               // address_span_extender_0_windowed_slave_agent:rf_source_data -> address_span_extender_0_windowed_slave_agent_rsp_fifo:in_data
	wire          address_span_extender_0_windowed_slave_agent_rf_source_ready;              // address_span_extender_0_windowed_slave_agent_rsp_fifo:in_ready -> address_span_extender_0_windowed_slave_agent:rf_source_ready
	wire          address_span_extender_0_windowed_slave_agent_rf_source_startofpacket;      // address_span_extender_0_windowed_slave_agent:rf_source_startofpacket -> address_span_extender_0_windowed_slave_agent_rsp_fifo:in_startofpacket
	wire          address_span_extender_0_windowed_slave_agent_rf_source_endofpacket;        // address_span_extender_0_windowed_slave_agent:rf_source_endofpacket -> address_span_extender_0_windowed_slave_agent_rsp_fifo:in_endofpacket
	wire          address_span_extender_0_windowed_slave_agent_rsp_fifo_out_valid;           // address_span_extender_0_windowed_slave_agent_rsp_fifo:out_valid -> address_span_extender_0_windowed_slave_agent:rf_sink_valid
	wire  [135:0] address_span_extender_0_windowed_slave_agent_rsp_fifo_out_data;            // address_span_extender_0_windowed_slave_agent_rsp_fifo:out_data -> address_span_extender_0_windowed_slave_agent:rf_sink_data
	wire          address_span_extender_0_windowed_slave_agent_rsp_fifo_out_ready;           // address_span_extender_0_windowed_slave_agent:rf_sink_ready -> address_span_extender_0_windowed_slave_agent_rsp_fifo:out_ready
	wire          address_span_extender_0_windowed_slave_agent_rsp_fifo_out_startofpacket;   // address_span_extender_0_windowed_slave_agent_rsp_fifo:out_startofpacket -> address_span_extender_0_windowed_slave_agent:rf_sink_startofpacket
	wire          address_span_extender_0_windowed_slave_agent_rsp_fifo_out_endofpacket;     // address_span_extender_0_windowed_slave_agent_rsp_fifo:out_endofpacket -> address_span_extender_0_windowed_slave_agent:rf_sink_endofpacket
	wire          address_span_extender_0_windowed_slave_agent_rdata_fifo_src_valid;         // address_span_extender_0_windowed_slave_agent:rdata_fifo_src_valid -> address_span_extender_0_windowed_slave_agent_rdata_fifo:in_valid
	wire   [65:0] address_span_extender_0_windowed_slave_agent_rdata_fifo_src_data;          // address_span_extender_0_windowed_slave_agent:rdata_fifo_src_data -> address_span_extender_0_windowed_slave_agent_rdata_fifo:in_data
	wire          address_span_extender_0_windowed_slave_agent_rdata_fifo_src_ready;         // address_span_extender_0_windowed_slave_agent_rdata_fifo:in_ready -> address_span_extender_0_windowed_slave_agent:rdata_fifo_src_ready
	wire          cmd_mux_src_valid;                                                         // cmd_mux:src_valid -> address_span_extender_0_windowed_slave_agent:cp_valid
	wire  [134:0] cmd_mux_src_data;                                                          // cmd_mux:src_data -> address_span_extender_0_windowed_slave_agent:cp_data
	wire          cmd_mux_src_ready;                                                         // address_span_extender_0_windowed_slave_agent:cp_ready -> cmd_mux:src_ready
	wire    [0:0] cmd_mux_src_channel;                                                       // cmd_mux:src_channel -> address_span_extender_0_windowed_slave_agent:cp_channel
	wire          cmd_mux_src_startofpacket;                                                 // cmd_mux:src_startofpacket -> address_span_extender_0_windowed_slave_agent:cp_startofpacket
	wire          cmd_mux_src_endofpacket;                                                   // cmd_mux:src_endofpacket -> address_span_extender_0_windowed_slave_agent:cp_endofpacket
	wire          bridge_0_avalon_master_agent_cp_valid;                                     // bridge_0_avalon_master_agent:cp_valid -> router:sink_valid
	wire  [134:0] bridge_0_avalon_master_agent_cp_data;                                      // bridge_0_avalon_master_agent:cp_data -> router:sink_data
	wire          bridge_0_avalon_master_agent_cp_ready;                                     // router:sink_ready -> bridge_0_avalon_master_agent:cp_ready
	wire          bridge_0_avalon_master_agent_cp_startofpacket;                             // bridge_0_avalon_master_agent:cp_startofpacket -> router:sink_startofpacket
	wire          bridge_0_avalon_master_agent_cp_endofpacket;                               // bridge_0_avalon_master_agent:cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                                          // router:src_valid -> cmd_demux:sink_valid
	wire  [134:0] router_src_data;                                                           // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                                          // cmd_demux:sink_ready -> router:src_ready
	wire    [0:0] router_src_channel;                                                        // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                                                  // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                                                    // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          address_span_extender_0_windowed_slave_agent_rp_valid;                     // address_span_extender_0_windowed_slave_agent:rp_valid -> router_001:sink_valid
	wire  [134:0] address_span_extender_0_windowed_slave_agent_rp_data;                      // address_span_extender_0_windowed_slave_agent:rp_data -> router_001:sink_data
	wire          address_span_extender_0_windowed_slave_agent_rp_ready;                     // router_001:sink_ready -> address_span_extender_0_windowed_slave_agent:rp_ready
	wire          address_span_extender_0_windowed_slave_agent_rp_startofpacket;             // address_span_extender_0_windowed_slave_agent:rp_startofpacket -> router_001:sink_startofpacket
	wire          address_span_extender_0_windowed_slave_agent_rp_endofpacket;               // address_span_extender_0_windowed_slave_agent:rp_endofpacket -> router_001:sink_endofpacket
	wire          router_001_src_valid;                                                      // router_001:src_valid -> rsp_demux:sink_valid
	wire  [134:0] router_001_src_data;                                                       // router_001:src_data -> rsp_demux:sink_data
	wire          router_001_src_ready;                                                      // rsp_demux:sink_ready -> router_001:src_ready
	wire    [0:0] router_001_src_channel;                                                    // router_001:src_channel -> rsp_demux:sink_channel
	wire          router_001_src_startofpacket;                                              // router_001:src_startofpacket -> rsp_demux:sink_startofpacket
	wire          router_001_src_endofpacket;                                                // router_001:src_endofpacket -> rsp_demux:sink_endofpacket
	wire          cmd_demux_src0_valid;                                                      // cmd_demux:src0_valid -> crosser:in_valid
	wire  [134:0] cmd_demux_src0_data;                                                       // cmd_demux:src0_data -> crosser:in_data
	wire          cmd_demux_src0_ready;                                                      // crosser:in_ready -> cmd_demux:src0_ready
	wire    [0:0] cmd_demux_src0_channel;                                                    // cmd_demux:src0_channel -> crosser:in_channel
	wire          cmd_demux_src0_startofpacket;                                              // cmd_demux:src0_startofpacket -> crosser:in_startofpacket
	wire          cmd_demux_src0_endofpacket;                                                // cmd_demux:src0_endofpacket -> crosser:in_endofpacket
	wire          crosser_out_valid;                                                         // crosser:out_valid -> cmd_mux:sink0_valid
	wire  [134:0] crosser_out_data;                                                          // crosser:out_data -> cmd_mux:sink0_data
	wire          crosser_out_ready;                                                         // cmd_mux:sink0_ready -> crosser:out_ready
	wire    [0:0] crosser_out_channel;                                                       // crosser:out_channel -> cmd_mux:sink0_channel
	wire          crosser_out_startofpacket;                                                 // crosser:out_startofpacket -> cmd_mux:sink0_startofpacket
	wire          crosser_out_endofpacket;                                                   // crosser:out_endofpacket -> cmd_mux:sink0_endofpacket
	wire          rsp_demux_src0_valid;                                                      // rsp_demux:src0_valid -> crosser_001:in_valid
	wire  [134:0] rsp_demux_src0_data;                                                       // rsp_demux:src0_data -> crosser_001:in_data
	wire          rsp_demux_src0_ready;                                                      // crosser_001:in_ready -> rsp_demux:src0_ready
	wire    [0:0] rsp_demux_src0_channel;                                                    // rsp_demux:src0_channel -> crosser_001:in_channel
	wire          rsp_demux_src0_startofpacket;                                              // rsp_demux:src0_startofpacket -> crosser_001:in_startofpacket
	wire          rsp_demux_src0_endofpacket;                                                // rsp_demux:src0_endofpacket -> crosser_001:in_endofpacket
	wire          crosser_001_out_valid;                                                     // crosser_001:out_valid -> rsp_mux:sink0_valid
	wire  [134:0] crosser_001_out_data;                                                      // crosser_001:out_data -> rsp_mux:sink0_data
	wire          crosser_001_out_ready;                                                     // rsp_mux:sink0_ready -> crosser_001:out_ready
	wire    [0:0] crosser_001_out_channel;                                                   // crosser_001:out_channel -> rsp_mux:sink0_channel
	wire          crosser_001_out_startofpacket;                                             // crosser_001:out_startofpacket -> rsp_mux:sink0_startofpacket
	wire          crosser_001_out_endofpacket;                                               // crosser_001:out_endofpacket -> rsp_mux:sink0_endofpacket
	wire          address_span_extender_0_windowed_slave_agent_rdata_fifo_out_valid;         // address_span_extender_0_windowed_slave_agent_rdata_fifo:out_valid -> avalon_st_adapter:in_0_valid
	wire   [65:0] address_span_extender_0_windowed_slave_agent_rdata_fifo_out_data;          // address_span_extender_0_windowed_slave_agent_rdata_fifo:out_data -> avalon_st_adapter:in_0_data
	wire          address_span_extender_0_windowed_slave_agent_rdata_fifo_out_ready;         // avalon_st_adapter:in_0_ready -> address_span_extender_0_windowed_slave_agent_rdata_fifo:out_ready
	wire          avalon_st_adapter_out_0_valid;                                             // avalon_st_adapter:out_0_valid -> address_span_extender_0_windowed_slave_agent:rdata_fifo_sink_valid
	wire   [65:0] avalon_st_adapter_out_0_data;                                              // avalon_st_adapter:out_0_data -> address_span_extender_0_windowed_slave_agent:rdata_fifo_sink_data
	wire          avalon_st_adapter_out_0_ready;                                             // address_span_extender_0_windowed_slave_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire    [0:0] avalon_st_adapter_out_0_error;                                             // avalon_st_adapter:out_0_error -> address_span_extender_0_windowed_slave_agent:rdata_fifo_sink_error

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (28),
		.AV_DATA_W                   (64),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (8),
		.UAV_ADDRESS_W               (28),
		.UAV_BURSTCOUNT_W            (4),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (8),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) bridge_0_avalon_master_translator (
		.clk                    (clk_0_clk_clk),                                                             //                       clk.clk
		.reset                  (bridge_0_reset_reset_bridge_in_reset_reset),                                //                     reset.reset
		.uav_address            (bridge_0_avalon_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (bridge_0_avalon_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (bridge_0_avalon_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (bridge_0_avalon_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (bridge_0_avalon_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (bridge_0_avalon_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (bridge_0_avalon_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (bridge_0_avalon_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (bridge_0_avalon_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (bridge_0_avalon_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (bridge_0_avalon_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (bridge_0_avalon_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (bridge_0_avalon_master_waitrequest),                                        //                          .waitrequest
		.av_byteenable          (bridge_0_avalon_master_byteenable),                                         //                          .byteenable
		.av_read                (bridge_0_avalon_master_read),                                               //                          .read
		.av_readdata            (bridge_0_avalon_master_readdata),                                           //                          .readdata
		.av_write               (bridge_0_avalon_master_write),                                              //                          .write
		.av_writedata           (bridge_0_avalon_master_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                                      //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                      //               (terminated)
		.av_begintransfer       (1'b0),                                                                      //               (terminated)
		.av_chipselect          (1'b0),                                                                      //               (terminated)
		.av_readdatavalid       (),                                                                          //               (terminated)
		.av_lock                (1'b0),                                                                      //               (terminated)
		.av_debugaccess         (1'b0),                                                                      //               (terminated)
		.uav_clken              (),                                                                          //               (terminated)
		.av_clken               (1'b1),                                                                      //               (terminated)
		.uav_response           (2'b00),                                                                     //               (terminated)
		.av_response            (),                                                                          //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                      //               (terminated)
		.av_writeresponsevalid  ()                                                                           //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (25),
		.AV_DATA_W                      (64),
		.UAV_DATA_W                     (64),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (8),
		.UAV_BYTEENABLE_W               (8),
		.UAV_ADDRESS_W                  (28),
		.UAV_BURSTCOUNT_W               (4),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (8),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) address_span_extender_0_windowed_slave_translator (
		.clk                    (hps_0_h2f_user2_clock_clk),                                     //                      clk.clk
		.reset                  (address_span_extender_0_reset_reset_bridge_in_reset_reset),     //                    reset.reset
		.uav_address            (address_span_extender_0_windowed_slave_agent_m0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (address_span_extender_0_windowed_slave_agent_m0_burstcount),    //                         .burstcount
		.uav_read               (address_span_extender_0_windowed_slave_agent_m0_read),          //                         .read
		.uav_write              (address_span_extender_0_windowed_slave_agent_m0_write),         //                         .write
		.uav_waitrequest        (address_span_extender_0_windowed_slave_agent_m0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (address_span_extender_0_windowed_slave_agent_m0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (address_span_extender_0_windowed_slave_agent_m0_byteenable),    //                         .byteenable
		.uav_readdata           (address_span_extender_0_windowed_slave_agent_m0_readdata),      //                         .readdata
		.uav_writedata          (address_span_extender_0_windowed_slave_agent_m0_writedata),     //                         .writedata
		.uav_lock               (address_span_extender_0_windowed_slave_agent_m0_lock),          //                         .lock
		.uav_debugaccess        (address_span_extender_0_windowed_slave_agent_m0_debugaccess),   //                         .debugaccess
		.av_address             (address_span_extender_0_windowed_slave_address),                //      avalon_anti_slave_0.address
		.av_write               (address_span_extender_0_windowed_slave_write),                  //                         .write
		.av_read                (address_span_extender_0_windowed_slave_read),                   //                         .read
		.av_readdata            (address_span_extender_0_windowed_slave_readdata),               //                         .readdata
		.av_writedata           (address_span_extender_0_windowed_slave_writedata),              //                         .writedata
		.av_burstcount          (address_span_extender_0_windowed_slave_burstcount),             //                         .burstcount
		.av_byteenable          (address_span_extender_0_windowed_slave_byteenable),             //                         .byteenable
		.av_readdatavalid       (address_span_extender_0_windowed_slave_readdatavalid),          //                         .readdatavalid
		.av_waitrequest         (address_span_extender_0_windowed_slave_waitrequest),            //                         .waitrequest
		.av_begintransfer       (),                                                              //              (terminated)
		.av_beginbursttransfer  (),                                                              //              (terminated)
		.av_writebyteenable     (),                                                              //              (terminated)
		.av_lock                (),                                                              //              (terminated)
		.av_chipselect          (),                                                              //              (terminated)
		.av_clken               (),                                                              //              (terminated)
		.uav_clken              (1'b0),                                                          //              (terminated)
		.av_debugaccess         (),                                                              //              (terminated)
		.av_outputenable        (),                                                              //              (terminated)
		.uav_response           (),                                                              //              (terminated)
		.av_response            (2'b00),                                                         //              (terminated)
		.uav_writeresponsevalid (),                                                              //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                           //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (134),
		.PKT_ORI_BURST_SIZE_L      (132),
		.PKT_RESPONSE_STATUS_H     (131),
		.PKT_RESPONSE_STATUS_L     (130),
		.PKT_QOS_H                 (119),
		.PKT_QOS_L                 (119),
		.PKT_DATA_SIDEBAND_H       (117),
		.PKT_DATA_SIDEBAND_L       (117),
		.PKT_ADDR_SIDEBAND_H       (116),
		.PKT_ADDR_SIDEBAND_L       (116),
		.PKT_BURST_TYPE_H          (115),
		.PKT_BURST_TYPE_L          (114),
		.PKT_CACHE_H               (129),
		.PKT_CACHE_L               (126),
		.PKT_THREAD_ID_H           (122),
		.PKT_THREAD_ID_L           (122),
		.PKT_BURST_SIZE_H          (113),
		.PKT_BURST_SIZE_L          (111),
		.PKT_TRANS_EXCLUSIVE       (105),
		.PKT_TRANS_LOCK            (104),
		.PKT_BEGIN_BURST           (118),
		.PKT_PROTECTION_H          (125),
		.PKT_PROTECTION_L          (123),
		.PKT_BURSTWRAP_H           (110),
		.PKT_BURSTWRAP_L           (110),
		.PKT_BYTE_CNT_H            (109),
		.PKT_BYTE_CNT_L            (106),
		.PKT_ADDR_H                (99),
		.PKT_ADDR_L                (72),
		.PKT_TRANS_COMPRESSED_READ (100),
		.PKT_TRANS_POSTED          (101),
		.PKT_TRANS_WRITE           (102),
		.PKT_TRANS_READ            (103),
		.PKT_DATA_H                (63),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (71),
		.PKT_BYTEEN_L              (64),
		.PKT_SRC_ID_H              (120),
		.PKT_SRC_ID_L              (120),
		.PKT_DEST_ID_H             (121),
		.PKT_DEST_ID_L             (121),
		.ST_DATA_W                 (135),
		.ST_CHANNEL_W              (1),
		.AV_BURSTCOUNT_W           (4),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) bridge_0_avalon_master_agent (
		.clk                   (clk_0_clk_clk),                                                             //       clk.clk
		.reset                 (bridge_0_reset_reset_bridge_in_reset_reset),                                // clk_reset.reset
		.av_address            (bridge_0_avalon_master_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (bridge_0_avalon_master_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (bridge_0_avalon_master_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (bridge_0_avalon_master_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (bridge_0_avalon_master_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (bridge_0_avalon_master_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (bridge_0_avalon_master_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (bridge_0_avalon_master_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (bridge_0_avalon_master_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (bridge_0_avalon_master_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (bridge_0_avalon_master_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (bridge_0_avalon_master_agent_cp_valid),                                     //        cp.valid
		.cp_data               (bridge_0_avalon_master_agent_cp_data),                                      //          .data
		.cp_startofpacket      (bridge_0_avalon_master_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (bridge_0_avalon_master_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (bridge_0_avalon_master_agent_cp_ready),                                     //          .ready
		.rp_valid              (rsp_mux_src_valid),                                                         //        rp.valid
		.rp_data               (rsp_mux_src_data),                                                          //          .data
		.rp_channel            (rsp_mux_src_channel),                                                       //          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                                 //          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                                   //          .endofpacket
		.rp_ready              (rsp_mux_src_ready),                                                         //          .ready
		.av_response           (),                                                                          // (terminated)
		.av_writeresponsevalid ()                                                                           // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (134),
		.PKT_ORI_BURST_SIZE_L      (132),
		.PKT_RESPONSE_STATUS_H     (131),
		.PKT_RESPONSE_STATUS_L     (130),
		.PKT_BURST_SIZE_H          (113),
		.PKT_BURST_SIZE_L          (111),
		.PKT_TRANS_LOCK            (104),
		.PKT_BEGIN_BURST           (118),
		.PKT_PROTECTION_H          (125),
		.PKT_PROTECTION_L          (123),
		.PKT_BURSTWRAP_H           (110),
		.PKT_BURSTWRAP_L           (110),
		.PKT_BYTE_CNT_H            (109),
		.PKT_BYTE_CNT_L            (106),
		.PKT_ADDR_H                (99),
		.PKT_ADDR_L                (72),
		.PKT_TRANS_COMPRESSED_READ (100),
		.PKT_TRANS_POSTED          (101),
		.PKT_TRANS_WRITE           (102),
		.PKT_TRANS_READ            (103),
		.PKT_DATA_H                (63),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (71),
		.PKT_BYTEEN_L              (64),
		.PKT_SRC_ID_H              (120),
		.PKT_SRC_ID_L              (120),
		.PKT_DEST_ID_H             (121),
		.PKT_DEST_ID_L             (121),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (1),
		.ST_DATA_W                 (135),
		.AVS_BURSTCOUNT_W          (4),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) address_span_extender_0_windowed_slave_agent (
		.clk                     (hps_0_h2f_user2_clock_clk),                                               //             clk.clk
		.reset                   (address_span_extender_0_reset_reset_bridge_in_reset_reset),               //       clk_reset.reset
		.m0_address              (address_span_extender_0_windowed_slave_agent_m0_address),                 //              m0.address
		.m0_burstcount           (address_span_extender_0_windowed_slave_agent_m0_burstcount),              //                .burstcount
		.m0_byteenable           (address_span_extender_0_windowed_slave_agent_m0_byteenable),              //                .byteenable
		.m0_debugaccess          (address_span_extender_0_windowed_slave_agent_m0_debugaccess),             //                .debugaccess
		.m0_lock                 (address_span_extender_0_windowed_slave_agent_m0_lock),                    //                .lock
		.m0_readdata             (address_span_extender_0_windowed_slave_agent_m0_readdata),                //                .readdata
		.m0_readdatavalid        (address_span_extender_0_windowed_slave_agent_m0_readdatavalid),           //                .readdatavalid
		.m0_read                 (address_span_extender_0_windowed_slave_agent_m0_read),                    //                .read
		.m0_waitrequest          (address_span_extender_0_windowed_slave_agent_m0_waitrequest),             //                .waitrequest
		.m0_writedata            (address_span_extender_0_windowed_slave_agent_m0_writedata),               //                .writedata
		.m0_write                (address_span_extender_0_windowed_slave_agent_m0_write),                   //                .write
		.rp_endofpacket          (address_span_extender_0_windowed_slave_agent_rp_endofpacket),             //              rp.endofpacket
		.rp_ready                (address_span_extender_0_windowed_slave_agent_rp_ready),                   //                .ready
		.rp_valid                (address_span_extender_0_windowed_slave_agent_rp_valid),                   //                .valid
		.rp_data                 (address_span_extender_0_windowed_slave_agent_rp_data),                    //                .data
		.rp_startofpacket        (address_span_extender_0_windowed_slave_agent_rp_startofpacket),           //                .startofpacket
		.cp_ready                (cmd_mux_src_ready),                                                       //              cp.ready
		.cp_valid                (cmd_mux_src_valid),                                                       //                .valid
		.cp_data                 (cmd_mux_src_data),                                                        //                .data
		.cp_startofpacket        (cmd_mux_src_startofpacket),                                               //                .startofpacket
		.cp_endofpacket          (cmd_mux_src_endofpacket),                                                 //                .endofpacket
		.cp_channel              (cmd_mux_src_channel),                                                     //                .channel
		.rf_sink_ready           (address_span_extender_0_windowed_slave_agent_rsp_fifo_out_ready),         //         rf_sink.ready
		.rf_sink_valid           (address_span_extender_0_windowed_slave_agent_rsp_fifo_out_valid),         //                .valid
		.rf_sink_startofpacket   (address_span_extender_0_windowed_slave_agent_rsp_fifo_out_startofpacket), //                .startofpacket
		.rf_sink_endofpacket     (address_span_extender_0_windowed_slave_agent_rsp_fifo_out_endofpacket),   //                .endofpacket
		.rf_sink_data            (address_span_extender_0_windowed_slave_agent_rsp_fifo_out_data),          //                .data
		.rf_source_ready         (address_span_extender_0_windowed_slave_agent_rf_source_ready),            //       rf_source.ready
		.rf_source_valid         (address_span_extender_0_windowed_slave_agent_rf_source_valid),            //                .valid
		.rf_source_startofpacket (address_span_extender_0_windowed_slave_agent_rf_source_startofpacket),    //                .startofpacket
		.rf_source_endofpacket   (address_span_extender_0_windowed_slave_agent_rf_source_endofpacket),      //                .endofpacket
		.rf_source_data          (address_span_extender_0_windowed_slave_agent_rf_source_data),             //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                                           // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                                           //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                                            //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                                           //                .error
		.rdata_fifo_src_ready    (address_span_extender_0_windowed_slave_agent_rdata_fifo_src_ready),       //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (address_span_extender_0_windowed_slave_agent_rdata_fifo_src_valid),       //                .valid
		.rdata_fifo_src_data     (address_span_extender_0_windowed_slave_agent_rdata_fifo_src_data),        //                .data
		.m0_response             (2'b00),                                                                   //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                                                     //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (136),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) address_span_extender_0_windowed_slave_agent_rsp_fifo (
		.clk               (hps_0_h2f_user2_clock_clk),                                               //       clk.clk
		.reset             (address_span_extender_0_reset_reset_bridge_in_reset_reset),               // clk_reset.reset
		.in_data           (address_span_extender_0_windowed_slave_agent_rf_source_data),             //        in.data
		.in_valid          (address_span_extender_0_windowed_slave_agent_rf_source_valid),            //          .valid
		.in_ready          (address_span_extender_0_windowed_slave_agent_rf_source_ready),            //          .ready
		.in_startofpacket  (address_span_extender_0_windowed_slave_agent_rf_source_startofpacket),    //          .startofpacket
		.in_endofpacket    (address_span_extender_0_windowed_slave_agent_rf_source_endofpacket),      //          .endofpacket
		.out_data          (address_span_extender_0_windowed_slave_agent_rsp_fifo_out_data),          //       out.data
		.out_valid         (address_span_extender_0_windowed_slave_agent_rsp_fifo_out_valid),         //          .valid
		.out_ready         (address_span_extender_0_windowed_slave_agent_rsp_fifo_out_ready),         //          .ready
		.out_startofpacket (address_span_extender_0_windowed_slave_agent_rsp_fifo_out_startofpacket), //          .startofpacket
		.out_endofpacket   (address_span_extender_0_windowed_slave_agent_rsp_fifo_out_endofpacket),   //          .endofpacket
		.csr_address       (2'b00),                                                                   // (terminated)
		.csr_read          (1'b0),                                                                    // (terminated)
		.csr_write         (1'b0),                                                                    // (terminated)
		.csr_readdata      (),                                                                        // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                                    // (terminated)
		.almost_full_data  (),                                                                        // (terminated)
		.almost_empty_data (),                                                                        // (terminated)
		.in_empty          (1'b0),                                                                    // (terminated)
		.out_empty         (),                                                                        // (terminated)
		.in_error          (1'b0),                                                                    // (terminated)
		.out_error         (),                                                                        // (terminated)
		.in_channel        (1'b0),                                                                    // (terminated)
		.out_channel       ()                                                                         // (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (66),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (0),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (0),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) address_span_extender_0_windowed_slave_agent_rdata_fifo (
		.clk               (hps_0_h2f_user2_clock_clk),                                         //       clk.clk
		.reset             (address_span_extender_0_reset_reset_bridge_in_reset_reset),         // clk_reset.reset
		.in_data           (address_span_extender_0_windowed_slave_agent_rdata_fifo_src_data),  //        in.data
		.in_valid          (address_span_extender_0_windowed_slave_agent_rdata_fifo_src_valid), //          .valid
		.in_ready          (address_span_extender_0_windowed_slave_agent_rdata_fifo_src_ready), //          .ready
		.out_data          (address_span_extender_0_windowed_slave_agent_rdata_fifo_out_data),  //       out.data
		.out_valid         (address_span_extender_0_windowed_slave_agent_rdata_fifo_out_valid), //          .valid
		.out_ready         (address_span_extender_0_windowed_slave_agent_rdata_fifo_out_ready), //          .ready
		.csr_address       (2'b00),                                                             // (terminated)
		.csr_read          (1'b0),                                                              // (terminated)
		.csr_write         (1'b0),                                                              // (terminated)
		.csr_readdata      (),                                                                  // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                              // (terminated)
		.almost_full_data  (),                                                                  // (terminated)
		.almost_empty_data (),                                                                  // (terminated)
		.in_startofpacket  (1'b0),                                                              // (terminated)
		.in_endofpacket    (1'b0),                                                              // (terminated)
		.out_startofpacket (),                                                                  // (terminated)
		.out_endofpacket   (),                                                                  // (terminated)
		.in_empty          (1'b0),                                                              // (terminated)
		.out_empty         (),                                                                  // (terminated)
		.in_error          (1'b0),                                                              // (terminated)
		.out_error         (),                                                                  // (terminated)
		.in_channel        (1'b0),                                                              // (terminated)
		.out_channel       ()                                                                   // (terminated)
	);

	soc_system_mm_interconnect_0_router router (
		.sink_ready         (bridge_0_avalon_master_agent_cp_ready),         //      sink.ready
		.sink_valid         (bridge_0_avalon_master_agent_cp_valid),         //          .valid
		.sink_data          (bridge_0_avalon_master_agent_cp_data),          //          .data
		.sink_startofpacket (bridge_0_avalon_master_agent_cp_startofpacket), //          .startofpacket
		.sink_endofpacket   (bridge_0_avalon_master_agent_cp_endofpacket),   //          .endofpacket
		.clk                (clk_0_clk_clk),                                 //       clk.clk
		.reset              (bridge_0_reset_reset_bridge_in_reset_reset),    // clk_reset.reset
		.src_ready          (router_src_ready),                              //       src.ready
		.src_valid          (router_src_valid),                              //          .valid
		.src_data           (router_src_data),                               //          .data
		.src_channel        (router_src_channel),                            //          .channel
		.src_startofpacket  (router_src_startofpacket),                      //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                         //          .endofpacket
	);

	soc_system_mm_interconnect_0_router_001 router_001 (
		.sink_ready         (address_span_extender_0_windowed_slave_agent_rp_ready),         //      sink.ready
		.sink_valid         (address_span_extender_0_windowed_slave_agent_rp_valid),         //          .valid
		.sink_data          (address_span_extender_0_windowed_slave_agent_rp_data),          //          .data
		.sink_startofpacket (address_span_extender_0_windowed_slave_agent_rp_startofpacket), //          .startofpacket
		.sink_endofpacket   (address_span_extender_0_windowed_slave_agent_rp_endofpacket),   //          .endofpacket
		.clk                (hps_0_h2f_user2_clock_clk),                                     //       clk.clk
		.reset              (address_span_extender_0_reset_reset_bridge_in_reset_reset),     // clk_reset.reset
		.src_ready          (router_001_src_ready),                                          //       src.ready
		.src_valid          (router_001_src_valid),                                          //          .valid
		.src_data           (router_001_src_data),                                           //          .data
		.src_channel        (router_001_src_channel),                                        //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                                  //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                                     //          .endofpacket
	);

	soc_system_mm_interconnect_0_cmd_demux cmd_demux (
		.clk                (clk_0_clk_clk),                              //       clk.clk
		.reset              (bridge_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_src_ready),                           //      sink.ready
		.sink_channel       (router_src_channel),                         //          .channel
		.sink_data          (router_src_data),                            //          .data
		.sink_startofpacket (router_src_startofpacket),                   //          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                     //          .endofpacket
		.sink_valid         (router_src_valid),                           //          .valid
		.src0_ready         (cmd_demux_src0_ready),                       //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                       //          .valid
		.src0_data          (cmd_demux_src0_data),                        //          .data
		.src0_channel       (cmd_demux_src0_channel),                     //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),               //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                  //          .endofpacket
	);

	soc_system_mm_interconnect_0_cmd_mux cmd_mux (
		.clk                 (hps_0_h2f_user2_clock_clk),                                 //       clk.clk
		.reset               (address_span_extender_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                                         //       src.ready
		.src_valid           (cmd_mux_src_valid),                                         //          .valid
		.src_data            (cmd_mux_src_data),                                          //          .data
		.src_channel         (cmd_mux_src_channel),                                       //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                                 //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                                   //          .endofpacket
		.sink0_ready         (crosser_out_ready),                                         //     sink0.ready
		.sink0_valid         (crosser_out_valid),                                         //          .valid
		.sink0_channel       (crosser_out_channel),                                       //          .channel
		.sink0_data          (crosser_out_data),                                          //          .data
		.sink0_startofpacket (crosser_out_startofpacket),                                 //          .startofpacket
		.sink0_endofpacket   (crosser_out_endofpacket)                                    //          .endofpacket
	);

	soc_system_mm_interconnect_0_rsp_demux rsp_demux (
		.clk                (hps_0_h2f_user2_clock_clk),                                 //       clk.clk
		.reset              (address_span_extender_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_001_src_ready),                                      //      sink.ready
		.sink_channel       (router_001_src_channel),                                    //          .channel
		.sink_data          (router_001_src_data),                                       //          .data
		.sink_startofpacket (router_001_src_startofpacket),                              //          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                                //          .endofpacket
		.sink_valid         (router_001_src_valid),                                      //          .valid
		.src0_ready         (rsp_demux_src0_ready),                                      //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                                      //          .valid
		.src0_data          (rsp_demux_src0_data),                                       //          .data
		.src0_channel       (rsp_demux_src0_channel),                                    //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                              //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                                 //          .endofpacket
	);

	soc_system_mm_interconnect_0_rsp_mux rsp_mux (
		.clk                 (clk_0_clk_clk),                              //       clk.clk
		.reset               (bridge_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                          //       src.ready
		.src_valid           (rsp_mux_src_valid),                          //          .valid
		.src_data            (rsp_mux_src_data),                           //          .data
		.src_channel         (rsp_mux_src_channel),                        //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                  //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                    //          .endofpacket
		.sink0_ready         (crosser_001_out_ready),                      //     sink0.ready
		.sink0_valid         (crosser_001_out_valid),                      //          .valid
		.sink0_channel       (crosser_001_out_channel),                    //          .channel
		.sink0_data          (crosser_001_out_data),                       //          .data
		.sink0_startofpacket (crosser_001_out_startofpacket),              //          .startofpacket
		.sink0_endofpacket   (crosser_001_out_endofpacket)                 //          .endofpacket
	);

	altera_avalon_st_handshake_clock_crosser #(
		.DATA_WIDTH          (135),
		.BITS_PER_SYMBOL     (135),
		.USE_PACKETS         (1),
		.USE_CHANNEL         (1),
		.CHANNEL_WIDTH       (1),
		.USE_ERROR           (0),
		.ERROR_WIDTH         (1),
		.VALID_SYNC_DEPTH    (2),
		.READY_SYNC_DEPTH    (2),
		.USE_OUTPUT_PIPELINE (0)
	) crosser (
		.in_clk            (clk_0_clk_clk),                                             //        in_clk.clk
		.in_reset          (bridge_0_reset_reset_bridge_in_reset_reset),                //  in_clk_reset.reset
		.out_clk           (hps_0_h2f_user2_clock_clk),                                 //       out_clk.clk
		.out_reset         (address_span_extender_0_reset_reset_bridge_in_reset_reset), // out_clk_reset.reset
		.in_ready          (cmd_demux_src0_ready),                                      //            in.ready
		.in_valid          (cmd_demux_src0_valid),                                      //              .valid
		.in_startofpacket  (cmd_demux_src0_startofpacket),                              //              .startofpacket
		.in_endofpacket    (cmd_demux_src0_endofpacket),                                //              .endofpacket
		.in_channel        (cmd_demux_src0_channel),                                    //              .channel
		.in_data           (cmd_demux_src0_data),                                       //              .data
		.out_ready         (crosser_out_ready),                                         //           out.ready
		.out_valid         (crosser_out_valid),                                         //              .valid
		.out_startofpacket (crosser_out_startofpacket),                                 //              .startofpacket
		.out_endofpacket   (crosser_out_endofpacket),                                   //              .endofpacket
		.out_channel       (crosser_out_channel),                                       //              .channel
		.out_data          (crosser_out_data),                                          //              .data
		.in_empty          (1'b0),                                                      //   (terminated)
		.in_error          (1'b0),                                                      //   (terminated)
		.out_empty         (),                                                          //   (terminated)
		.out_error         ()                                                           //   (terminated)
	);

	altera_avalon_st_handshake_clock_crosser #(
		.DATA_WIDTH          (135),
		.BITS_PER_SYMBOL     (135),
		.USE_PACKETS         (1),
		.USE_CHANNEL         (1),
		.CHANNEL_WIDTH       (1),
		.USE_ERROR           (0),
		.ERROR_WIDTH         (1),
		.VALID_SYNC_DEPTH    (2),
		.READY_SYNC_DEPTH    (2),
		.USE_OUTPUT_PIPELINE (0)
	) crosser_001 (
		.in_clk            (hps_0_h2f_user2_clock_clk),                                 //        in_clk.clk
		.in_reset          (address_span_extender_0_reset_reset_bridge_in_reset_reset), //  in_clk_reset.reset
		.out_clk           (clk_0_clk_clk),                                             //       out_clk.clk
		.out_reset         (bridge_0_reset_reset_bridge_in_reset_reset),                // out_clk_reset.reset
		.in_ready          (rsp_demux_src0_ready),                                      //            in.ready
		.in_valid          (rsp_demux_src0_valid),                                      //              .valid
		.in_startofpacket  (rsp_demux_src0_startofpacket),                              //              .startofpacket
		.in_endofpacket    (rsp_demux_src0_endofpacket),                                //              .endofpacket
		.in_channel        (rsp_demux_src0_channel),                                    //              .channel
		.in_data           (rsp_demux_src0_data),                                       //              .data
		.out_ready         (crosser_001_out_ready),                                     //           out.ready
		.out_valid         (crosser_001_out_valid),                                     //              .valid
		.out_startofpacket (crosser_001_out_startofpacket),                             //              .startofpacket
		.out_endofpacket   (crosser_001_out_endofpacket),                               //              .endofpacket
		.out_channel       (crosser_001_out_channel),                                   //              .channel
		.out_data          (crosser_001_out_data),                                      //              .data
		.in_empty          (1'b0),                                                      //   (terminated)
		.in_error          (1'b0),                                                      //   (terminated)
		.out_empty         (),                                                          //   (terminated)
		.out_error         ()                                                           //   (terminated)
	);

	soc_system_mm_interconnect_0_avalon_st_adapter #(
		.inBitsPerSymbol (66),
		.inUsePackets    (0),
		.inDataWidth     (66),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (66),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (hps_0_h2f_user2_clock_clk),                                         // in_clk_0.clk
		.in_rst_0_reset (address_span_extender_0_reset_reset_bridge_in_reset_reset),         // in_rst_0.reset
		.in_0_data      (address_span_extender_0_windowed_slave_agent_rdata_fifo_out_data),  //     in_0.data
		.in_0_valid     (address_span_extender_0_windowed_slave_agent_rdata_fifo_out_valid), //         .valid
		.in_0_ready     (address_span_extender_0_windowed_slave_agent_rdata_fifo_out_ready), //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                                      //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                                     //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                                     //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                                      //         .error
	);

endmodule
