	soc_system u0 (
		.clk_clk                 (<connected-to-clk_clk>),                 //             clk.clk
		.hps_0_h2f_reset_reset_n (<connected-to-hps_0_h2f_reset_reset_n>), // hps_0_h2f_reset.reset_n
		.memory_mem_a            (<connected-to-memory_mem_a>),            //          memory.mem_a
		.memory_mem_ba           (<connected-to-memory_mem_ba>),           //                .mem_ba
		.memory_mem_ck           (<connected-to-memory_mem_ck>),           //                .mem_ck
		.memory_mem_ck_n         (<connected-to-memory_mem_ck_n>),         //                .mem_ck_n
		.memory_mem_cke          (<connected-to-memory_mem_cke>),          //                .mem_cke
		.memory_mem_cs_n         (<connected-to-memory_mem_cs_n>),         //                .mem_cs_n
		.memory_mem_ras_n        (<connected-to-memory_mem_ras_n>),        //                .mem_ras_n
		.memory_mem_cas_n        (<connected-to-memory_mem_cas_n>),        //                .mem_cas_n
		.memory_mem_we_n         (<connected-to-memory_mem_we_n>),         //                .mem_we_n
		.memory_mem_reset_n      (<connected-to-memory_mem_reset_n>),      //                .mem_reset_n
		.memory_mem_dq           (<connected-to-memory_mem_dq>),           //                .mem_dq
		.memory_mem_dqs          (<connected-to-memory_mem_dqs>),          //                .mem_dqs
		.memory_mem_dqs_n        (<connected-to-memory_mem_dqs_n>),        //                .mem_dqs_n
		.memory_mem_odt          (<connected-to-memory_mem_odt>),          //                .mem_odt
		.memory_mem_dm           (<connected-to-memory_mem_dm>),           //                .mem_dm
		.memory_oct_rzqin        (<connected-to-memory_oct_rzqin>),        //                .oct_rzqin
		.reset_reset_n           (<connected-to-reset_reset_n>),           //           reset.reset_n
		.sdram_address           (<connected-to-sdram_address>),           //           sdram.address
		.sdram_byte_enable       (<connected-to-sdram_byte_enable>),       //                .byte_enable
		.sdram_read              (<connected-to-sdram_read>),              //                .read
		.sdram_write             (<connected-to-sdram_write>),             //                .write
		.sdram_write_data        (<connected-to-sdram_write_data>),        //                .write_data
		.sdram_acknowledge       (<connected-to-sdram_acknowledge>),       //                .acknowledge
		.sdram_read_data         (<connected-to-sdram_read_data>),         //                .read_data
		.uart_out_ready          (<connected-to-uart_out_ready>),          //        uart_out.ready
		.uart_out_data           (<connected-to-uart_out_data>),           //                .data
		.uart_out_error          (<connected-to-uart_out_error>),          //                .error
		.uart_out_valid          (<connected-to-uart_out_valid>),          //                .valid
		.uart_in_data            (<connected-to-uart_in_data>),            //         uart_in.data
		.uart_in_error           (<connected-to-uart_in_error>),           //                .error
		.uart_in_valid           (<connected-to-uart_in_valid>),           //                .valid
		.uart_in_ready           (<connected-to-uart_in_ready>),           //                .ready
		.uart_RXD                (<connected-to-uart_RXD>),                //            uart.RXD
		.uart_TXD                (<connected-to-uart_TXD>)                 //                .TXD
	);

