	soc_system u0 (
		.clk_clk                        (<connected-to-clk_clk>),                        //                        clk.clk
		.hps_0_h2f_reset_reset_n        (<connected-to-hps_0_h2f_reset_reset_n>),        //            hps_0_h2f_reset.reset_n
		.memory_mem_a                   (<connected-to-memory_mem_a>),                   //                     memory.mem_a
		.memory_mem_ba                  (<connected-to-memory_mem_ba>),                  //                           .mem_ba
		.memory_mem_ck                  (<connected-to-memory_mem_ck>),                  //                           .mem_ck
		.memory_mem_ck_n                (<connected-to-memory_mem_ck_n>),                //                           .mem_ck_n
		.memory_mem_cke                 (<connected-to-memory_mem_cke>),                 //                           .mem_cke
		.memory_mem_cs_n                (<connected-to-memory_mem_cs_n>),                //                           .mem_cs_n
		.memory_mem_ras_n               (<connected-to-memory_mem_ras_n>),               //                           .mem_ras_n
		.memory_mem_cas_n               (<connected-to-memory_mem_cas_n>),               //                           .mem_cas_n
		.memory_mem_we_n                (<connected-to-memory_mem_we_n>),                //                           .mem_we_n
		.memory_mem_reset_n             (<connected-to-memory_mem_reset_n>),             //                           .mem_reset_n
		.memory_mem_dq                  (<connected-to-memory_mem_dq>),                  //                           .mem_dq
		.memory_mem_dqs                 (<connected-to-memory_mem_dqs>),                 //                           .mem_dqs
		.memory_mem_dqs_n               (<connected-to-memory_mem_dqs_n>),               //                           .mem_dqs_n
		.memory_mem_odt                 (<connected-to-memory_mem_odt>),                 //                           .mem_odt
		.memory_mem_dm                  (<connected-to-memory_mem_dm>),                  //                           .mem_dm
		.memory_oct_rzqin               (<connected-to-memory_oct_rzqin>),               //                           .oct_rzqin
		.reset_reset_n                  (<connected-to-reset_reset_n>),                  //                      reset.reset_n
		.sdram_address                  (<connected-to-sdram_address>),                  //                      sdram.address
		.sdram_byte_enable              (<connected-to-sdram_byte_enable>),              //                           .byte_enable
		.sdram_read                     (<connected-to-sdram_read>),                     //                           .read
		.sdram_write                    (<connected-to-sdram_write>),                    //                           .write
		.sdram_write_data               (<connected-to-sdram_write_data>),               //                           .write_data
		.sdram_acknowledge              (<connected-to-sdram_acknowledge>),              //                           .acknowledge
		.sdram_read_data                (<connected-to-sdram_read_data>),                //                           .read_data
		.uart_0_external_connection_rxd (<connected-to-uart_0_external_connection_rxd>), // uart_0_external_connection.rxd
		.uart_0_external_connection_txd (<connected-to-uart_0_external_connection_txd>), //                           .txd
		.uart_bridge_s0_waitrequest     (<connected-to-uart_bridge_s0_waitrequest>),     //             uart_bridge_s0.waitrequest
		.uart_bridge_s0_readdata        (<connected-to-uart_bridge_s0_readdata>),        //                           .readdata
		.uart_bridge_s0_readdatavalid   (<connected-to-uart_bridge_s0_readdatavalid>),   //                           .readdatavalid
		.uart_bridge_s0_burstcount      (<connected-to-uart_bridge_s0_burstcount>),      //                           .burstcount
		.uart_bridge_s0_writedata       (<connected-to-uart_bridge_s0_writedata>),       //                           .writedata
		.uart_bridge_s0_address         (<connected-to-uart_bridge_s0_address>),         //                           .address
		.uart_bridge_s0_write           (<connected-to-uart_bridge_s0_write>),           //                           .write
		.uart_bridge_s0_read            (<connected-to-uart_bridge_s0_read>),            //                           .read
		.uart_bridge_s0_byteenable      (<connected-to-uart_bridge_s0_byteenable>),      //                           .byteenable
		.uart_bridge_s0_debugaccess     (<connected-to-uart_bridge_s0_debugaccess>)      //                           .debugaccess
	);

